### PR TITLE
Fire delegate to know when data has been successfully send to server.

### PR DESCRIPTION
**Pull request by jesuslg123**
Now every time data is deliveried to the server, there is a callback, to know that it has been sucessfully sent.
Also if you call send data when server is down, is was keeping waiting to finish operation, so I have changed to cancell all operation if something goes wrong.

### CODE REVIEW

**Comment by acmacalister** [comment]
Sorry if delay in looking over this. The code looks good, I guess I'm just a little confused on what the use case would be? Do you have a situation where you needed a callback to know about every message the client sent?

**Comment by jesuslg123** [comment]
Hi. On my code implementation, I send message one by one as fast as possible. If I  send 5 messages and after X seconds I get an error, I don't know which message has fail or not to retry again. Adding this I can now that message has been sent OK, and process the next one or wait and retry. It's makes sense?
Thanks

**Comment by adamkaplan** [comment]
Both behaviors make assumptions about the client intention. Waiting for all operations is just as wrong as canceling them. I suggest changing one of these approaches:

1. `-flush` synchronous blocking method to allow clients the _option_ of closing safely.
2. Boolean flag version of `-close` to indicate if it should be a force close.

Also I haven't thought much about this: but could a steady stream of incoming messages delay socket close with the current setup?

**Comment by daltoniam** [comment]
I agree, they are make assumptions, but I think those assumptions might make sense :smile:. I am not certain how canceling the operations in the write queue would be the wrong behavior. The stream has been disconnected, so any messages that attempt to be written will fail anyway. I believe waiting for the operations (as it is in the current state, which seems incorrect) is less than ideal as it is just waiting for operations that are going to fail and it is doing it synchronously, which won't block the main thread since it is on the background thread still. That being said, no reason to have unneeded delay.

I doubt that incoming messages would cause a close delay. Once the NSStream sends a disconnect code to its delegate (jetfire) it calls `disconnectStream` which closes the streams and removes them from the runloops. I haven't tested that to be sure, but I think the code's logic would point to that not being an issue.

As far as the PR goes, I think we should cherry pick the `cancelAllOperations` and leave out the `didWriteSuccessfully` delegate method. Even if the message has been successfully written to the socket there isn't a guarantee that it made it to the server. I would think the server should respond back that it got the message to confirm to the client it was received. 

Thoughts? I appreciate all the feedback, got to love open source :smile:.

**Comment by adamkaplan** [comment]
I guess the point was that there is correctness in both approaches. Discarding outstanding requests is guaranteed to piss somebody off later on. Forcing all clients to wait for pending data to transmit didn't work for your use case.

When in doubt, fall back to established APIs. C works in this example... calling `fclose()` will close a file after flushing pending write data. On the other hand, calling `fpurge() && flose();` will discard outstanding write bytes and close the file immediately.

Could you take a similar approach here buy add something like `-purge`?

You found a legit problem. It should be fixed in a way that follows the principal of least surprise, which in this case is pretty trivial to do. wdyt?

**Comment by daltoniam** [comment]
I agree. Since the `disconnectStream` could happen at anytime, I think we might want to have something like a pending operations array that has all the operations that hadn't completed yet in the `websocketDidDisconnect:`. This way a user could see all the opts written and know which ones hadn't finished. The could choose to reschedule them or not and resolves the underlining issue for this PR.

**Comment by adamkaplan** [comment]
@daltoniam That's a good idea and should be added regardless! It doesn't actually solve the problem I see, which is no flush-like method.

I've designed a lot of SDKs and one personal requirement that will get you very far is to design APIs to require the least work from the implementing clients. The common case I see is:

App backgrounded –> Need to send pending data & close connection.

In this case both canceling all operations or not canceling them is problematic. With the former clients lose data immediately, with the later, clients lose data if the connection doesn't end before watchdog takes notice. My issue with the suggestion is that it *requires* clients to deal with unsent data. 

I suspect that the common case will be that the client needs it's pending data to be sent within some time interval, on app background, say 30 seconds. Sound reasonable?

So the flow I see would be:

1. App backgrounded
2. Client calls flush-like method, which (blocking? async?) waits for all data to be sent.
3. Client sets N second timer
4a. All data sent within N seconds via flush & client closes connection
4b. Timer expires, client calls disconnect
5. Client receives delegate callback with unsent data

With this flow, handling step 5 becomes an edge case that developers can optimize around. Make sense?

*Side Note:*
When using `cancelAllOperations`, what happens to any operation(s) that are in-progress when the output stream is closed underneath it?

**Comment by daltoniam** [comment]
@adamkaplan thanks for the write up. I understand what you are getting at now, makes sense. My thought is that the current `disconnect` method just adds a close opt to the write queue, which is basically like doing a flush and close. When the server gets this opt, the client's stream is disconnected and ideally there shouldn't be any other opts left to write, since the close opt was the last in the write queue. The app user could just use `beginBackgroundTaskWithName:` until the task is finished, then will get the delegate callback when the socket gets disconnected (and with the other change suggested, know which opts didn't finish in the time limit, if any). Am I missing some kind of use case with this proposal?

I believe `NSOperationQueue` are thread safe and can be called from any thread. For the the stream, the queue only allows one to write at a time, so I would think the outputStream would just sit and wait for more bytes that would never come and is going to be cleanup almost immediately anyway.

**Comment by adamkaplan** [comment]
>  believe NSOperationQueue are thread safe and can be called from any thread. For the the stream, the queue only allows one to write at a time, so I would think the outputStream would just sit and wait for more bytes that would never come and is going to be cleanup almost immediately anyway.

Right, but calling `cancel` on an in-progress NSOperation does not abort execution. So, is it safe to call NSOutputStream's `write:` method on one thread, and at the same time call `close` on another thread? I honestly do not know, but it got me thinking...  IMO, with these cases you either prove that it is a safe operation, or even better, default to not doing it.

**Comment by jesuslg123** [comment]
Closing as its has been long time since it was opened. Thanks.

**Pull request closed without merging**
