### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by soffes**

### CODE REVIEW

**Comment by acmacalister** [comment]
Thanks. Appreciate it!

**Comment by soffes** [comment]
Can you tag, release, and add a prebuilt library to the release on GitHub? Here's how to create a Carthage archive:

    $ carthage build --no-skip-current && carthage archive Jetfire

:heart:

**Comment by acmacalister** [comment]
@soffes done. I attached the framework in the 0.1.6 release.

**Comment by soffes** [comment]
:heart: thanks so much!

**Pull request merged**
