### PR TITLE
Updated version as promised in issue #29

### PR DESCRIPTION
**Pull request by BarryHaanstra**

### CODE REVIEW

**Comment by acmacalister** [comment]
Sorry about that. Got caught up with some other things and just hadn't got a chance to update the pod. I do that right after I merge your PR. I'm looking to port some of the Starscream code over as I think it has a lot of fixes Jetfire could use. Just haven't got a chance to sit down and do it yet. :smile:

**Comment by BarryHaanstra** [comment]
Thanks for the quick response! :)

**Comment by acmacalister** [comment]
0.1.3 should be out now. :smile:

**Comment by BarryHaanstra** [comment]
Awesome!

**Pull request merged**
