### PR TITLE
Bug Fix

### PR DESCRIPTION
**Pull request by dorada**
This change fixes a thread hang in [self.writeQueue
waitUntilAllOperationsAreFinished] when doWriteError is called from
within dequeueWrite:withCode

### CODE REVIEW

**Comment by acmacalister** [comment]
Thanks for the fix!

**Comment by BarryHaanstra** [comment]
I think the dispatch_async to doWriteError can be removed because my fix already dispatches in the doWriteError method itself, so now it's double

**Comment by acmacalister** [comment]
Hey @BarryHaanstra, good catch. Give me a few minutes, I'm just going to sit down and port the Starscream stuff real quick and 0.1.4 should be coming your way shortly.

**Comment by acmacalister** [comment]
@BarryHaanstra 0.1.4 should be on per with Starscream and have that duplicate dispatch_async removed.

**Comment by BarryHaanstra** [comment]
Thanks again!

**Pull request merged**
